environment:
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_TOOLCHAIN: stable

branches:
  only:
    - master

cache:
  - '%USERPROFILE%\.cargo -> Cargo.toml, **\Cargo.toml'
  - '%APPVEYOR_BUILD_FOLDER%\target -> Cargo.toml, **\Cargo.toml'

clone_depth: 1

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"

platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  - cargo check --verbose --release --lib --tests

test_script:
  - |-
    cargo test --verbose --release
    cargo test --release --manifest-path rust_sodium-sys/Cargo.toml
